name: "[Auth] - Publish Docker auth service"
on:
 push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: MathieuGery/MyTelegram/back-authentification
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}
          registry: docker.pkg.github.com
          workdir: back/auth
