name: "[Chat Server] - Publish Docker chat server"
on:
 push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: MathieuGery/MyTelegram/chat-server
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}
          registry: docker.pkg.github.com
          workdir: back/chat
